### ISSUE TITLE
Okular Icon

### ISSUE THREAD

**Issue by jcuenod** [gusbemacbe/suru-plus#38] opened 2018-09-28 03:02 UTC
Could you add an icon for Okular. Okular is (I think) the standard pdf reading application on KDE:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/KDE-graphics-viewer-document.svg/128px-KDE-graphics-viewer-document.svg.png" />

```
[Desktop Entry]
Type=Application
Name=Okular
GenericName=Document Viewer
Icon=okular
Categories=Qt;KDE;Graphics;Viewer;
```

**Comment by gusbemacbe** [comment] 2018-09-28 03:14
Hi,

I have already added it before. Here is the https://github.com/gusbemacbe/suru-plus/blob/master/apps/scalable/document/okular.svg.

I will investigate why this icon is not well displayed in Okular.

**Comment by jcuenod** [comment] 2018-09-28 03:30
I see that now. Sorry.

Hmm, for me the icon is displaying when I search for Okular in the applications menu but it's not showing up in the alt-tab dialog.

**Comment by gusbemacbe** [comment] 2018-09-28 03:32
> Hmm, for me the icon is displaying when I search for Okular in the applications menu but it's not showing up in the alt-tab dialog.

Then it must be rendering bug. I will investigate it.

**Comment by jcuenod** [comment] 2018-09-28 03:37
Thanks!

**Comment by gusbemacbe** [comment] 2018-09-28 03:49
I can not replicate this issue because the icon is well rendered when I pressed alt+tab:

![image](https://user-images.githubusercontent.com/2257024/46187083-385a1980-c2b8-11e8-874e-357a2c148b3c.png)

I know you are a KDE user, but what distribution of Linux do you use?

**Comment by gusbemacbe** [comment] 2018-09-28 17:09
OK, I will test it on Manjaro GNOME.

**Comment by jcuenod** [comment] 2018-09-29 14:27
I figured out the reason (I think): https://unix.stackexchange.com/questions/387614/modify-desktop-application-icon-after-progam-opens-e-g-in-alt-tab

Basically Okular's `.desktop` files are stupid:

```
okularApplication_chm.desktop        okularApplication_md.desktop
okularApplication_comicbook.desktop  okularApplication_mobi.desktop
okularApplication_djvu.desktop       okularApplication_ooo.desktop
okularApplication_dvi.desktop        okularApplication_pdf.desktop
okularApplication_epub.desktop       okularApplication_plucker.desktop
okularApplication_fax.desktop        okularApplication_tiff.desktop
okularApplication_fb.desktop         okularApplication_txt.desktop
okularApplication_ghostview.desktop  okularApplication_xps.desktop
okularApplication_kimgio.desktop
```

So gnome-shell doesn't know that the `okular` window belongs to any of those `.desktop` files.

**Comment by jcuenod** [comment] 2018-09-29 18:28
Maybe symlinking each of those names to okular.svg would be a decent solution?

`okularApplication_pdf.svg -> okular.svg`

**Comment by gusbemacbe** [comment] 2018-09-29 18:57
Yes, symlink is the solution to keep the size economic.

**Comment by gusbemacbe** [comment] 2018-09-29 23:54
I have checked all the Okular desktop files, but almost they use the same icon name. I have solved the bug, it was Gravit Designer metadata with base64 which prevented Okular (symlinked t document.svg) icon from being rendered, in reference to https://github.com/gusbemacbe/suru-plus/pull/34#issuecomment-425668398. Please download and test the [unstable branch](/gusbemacbe/suru-plus/tree/unstable).

**Comment by gusbemacbe** [comment] 2018-10-13 21:59
Please, @jcuenod 

Please test the [unstable branch](/gusbemacbe/suru-plus/tree/unstable). If it works, it will be merged into the master branch tomorrow.

**Comment by jcuenod** [comment] 2018-10-14 01:38
Hmm, this didn't work for me.

**Comment by jcuenod** [comment] 2018-10-14 01:43
Can you point me to the commit that should fix this because I'm not seeing the symlinks (I don't know where to look though - I checked `scalable` and `scalable/document`

**Comment by gusbemacbe** [comment] 2018-10-14 08:04
Sorry, I forgot of copying the files. I was in much hurry. I have just uploaded. It is in the branch unstable-emergence.

**Comment by gusbemacbe** [comment] 2018-10-14 09:17
You are added in the files AUTHORS and CHANGELG.

**Comment by gusbemacbe** [comment] 2018-10-14 12:13
I credited you at my produt pagt at OpenDesktop. Unfortunately OpenDesktop is broken now.

**Comment by jcuenod** [comment] 2018-10-14 17:02
For some reason I'm still having trouble.
I see all the symlinks but the icon is not changing for the `alt-tab` dialog. I tried regenerating the cache but it didn't help. Any suggestions?

**Comment by gusbemacbe** [comment] 2018-10-14 22:44
It can be KDE rendering bug or issue. I will check if there is something dirty in Okular icon.

**Comment by jcuenod** [comment] 2018-10-14 23:00
It does show up in the applications overview, just not the alt-tab dialog. So it still seems like a window class issue.

**Comment by gusbemacbe** [comment] 2018-10-14 23:09
It works on Manjaro KDE:

![image](https://user-images.githubusercontent.com/2257024/46923347-c8080380-cfec-11e8-8ebf-b118178f6b75.png)

Then it must be KDE bug (because Okular is written in KDE). 

But I will install Antergos with GNOME to investigate the cause.

**Comment by gusbemacbe** [comment] 2018-10-15 00:37
In Antergos, I have noticed that using NUmix as efaut theme, the icon is having bad quality. You can see how the icon got a bit pixelated:

![image](https://user-images.githubusercontent.com/2257024/46924072-030f3480-cff7-11e8-8728-289fec4cd2a5.png)

I set my icons theme. It still uses Numix icon instead of my icon. I understood what happened... As they are written in KDE, all the okular desktop files do not have StartupWMClass entrance, therefore, the KDE apps do not fit well on GNOME.

**Comment by gusbemacbe** [comment] 2018-10-15 00:45
With StartupWMClass added in the desktop file, the icon returned to the normal, here:

![image](https://user-images.githubusercontent.com/2257024/46924320-f50ee300-cff9-11e8-89a0-7480b2e9b97b.png)

It is why the KDE apps deskto files do not have StartupWMClass.

**Comment by gusbemacbe** [comment] 2018-10-15 00:45
Hey @palob and @Foggalong, I do not know if you are working with Antergos.

Due the lack of StartupWMClass, Numix icons get pixelated in KDE apps on GNOME. And in addition, if somebody changes the icons theme, the icon will not be well displayed. 

If adding StartupWMCClass, Numix icons will get unpixelated and return to the normal.

**Comment by palob** [comment] 2018-10-15 06:46
We are not currently officially affiliated with the Antergos project. Since it is an issue we've got no leverage on I only can direct you to https://github.com/bilelmoussaoui/StartupWMClassFixer.

**Comment by jcuenod** [comment] 2018-10-16 04:56
Surely there's a better way than modifying the `.desktop` files? Why do the Numix icons work (even if they're showing some sort of pixelated version)?

**Comment by gusbemacbe** [comment] 2018-10-16 10:11
Hey @jcuenod 

It is the default theme of Antergos. I did not install Numix. It came with Numix as default. 

You can try to install [StartupWMClassFixer](https://github.com/bilelmoussaoui/StartupWMClassFixer).

Or maybe ask @bilelmoussaoui. He may know.

**Comment by bilelmoussaoui** [comment] 2018-10-16 10:34
Hey, the startupwmclass is used to match the desktop file with the running processes. It's an issue with either the application itself or the window manager you're using. The only way to fix it here without any source code patches is using the startupwmclass script mentioned before or by adding it manually.

**Comment by gusbemacbe** [comment] 2018-10-18 13:12
@jcuenod, I suspect it be a KDE cache bug which prevented the update of StartupWMClass. Check if you have still icon-cache.kcache.

**Comment by jcuenod** [comment] 2018-10-19 00:48
@gusbemacbe maybe I'm wrong but I don't think I have a `icon-cache.kcache` file. I use gnome.

**Comment by gusbemacbe** [comment] 2019-01-21 22:05
@jcuenod 

Finally, the problem is the icons cache. I recommend you to use Stacer which will clear the cache and refresh the icons theme. Then log out and log in.

**Closed** 2019-01-26 06:57 UTC
Labels: GNOME, bug
